### ISSUE TITLE
Alias problem

### ISSUE THREAD

**Issue by shilangyu** [tc39/proposal-array-filtering#1]
While I agree that the `filter` method is very confusing, a thing I would hate more is having aliases. `Array.prototype.filter` will most likely **not** be removed/deprecated when `select` will make its way into JavaScript. Which will mean we will have 2 1:1 methods. My 2 cents are that I support this proposal only if it will ensure that programmers wont have to choose between `filter` and `select`.

**Comment by edongashi** [comment]
In .NET's LINQ `enumerable.Select(x => ...)` means a projection (Array.map). People coming from C# would certainly be confused.

**Comment by jridgewell** [comment]
> Which will mean we will have 2 1:1 methods. My 2 cents are that I support this proposal only if it will ensure that programmers wont have to choose between filter and select.

I think this falls into a linter concern. Certainly seeing mixed use of `.filter` and `.select` isn't ideal, but but giving people the option to choose `.select` is worth it to both the writer and reader.

Note that we have other aliases already in the language:

- `Set.prototype.keys` is an alias of `Set.prototype.values`
- `String.prototype.trimLeft` is an alias of `String.prototype.trimStart`
- `String.prototype.trimRight` is an alias of `String.prototype.trimEnd`

(That's not including the aliases from the `@@iterator` to some other method)

**Comment by ljharb** [comment]
To be fair tho, in the first case, that’s because the protocol requires all three of keys/values/entries; in the second two, that’s because the right/left variants were impossible to remove, and ended up effectively deprecated, in annex b.

I don’t think any of those three serves as precedent for this proposal.

**Comment by hax** [comment]
Maybe only add `Array.p.filterOut` ?

**Comment by jridgewell** [comment]
> that’s because the right/left variants were impossible to remove, and ended up effectively deprecated, in annex b.

Annex B doesn't mean deprecated.

> Maybe only add `Array.p.filterOut` ?

That's another possibility, but it doesn't help with `filter` doing the opposite of what it should.

**Comment by hax** [comment]
> it doesn't help with `filter` doing the opposite of what it should

With both `filter/filterOut` in IDE's autocomplete list , I guess the programmers may reason out they will have opposite behavior... 😂

**Comment by jridgewell** [comment]
> in IDE's autocomplete list , I guess the programmers may reason out they will have opposite behavior... 😂

And when reading, when there's no autocomplete list? Or people who just use and editor and not and IDE (like me)?

**Comment by ljharb** [comment]
Annex B means many potential things; absolutely one of them is “deprecated”.

**Comment by ckknight** [comment]
I love the idea of a `reject` method on `Array.prototype`. Or it could be called `filterOut` or any other name that makes sense and fits within our existing ecosystem.

The `select` name makes sense if one comes from a Ruby background, but does not if one comes from a LISP, .NET, Java, or SQL background.

One potential issue I see with `reject` is that `Array.prototype.reject` is _very_ different from `Promise.reject` despite sharing the same name. It could lead to some confusion.

As an aside, if we add `reject`, it might be appropriate to add `partition` that could act similarly to https://lodash.com/docs/4.17.15#partition — this also might be out-of-scope.

**Comment by MaxGraey** [comment]
yeah, I also thought about `partition`. But it seems this out of scope: https://github.com/jridgewell/proposal-array-select-reject/issues/2

**Comment by jridgewell** [comment]
> LISP, .NET, Java, or SQL

I know what `SELECT` does in SQL, but how about the other languages?

**Comment by MaxGraey** [comment]
For example in LINQ (C#) [`Select` is analog of Array.p.map](https://docs.microsoft.com/en-us/dotnet/api/system.linq.enumerable.select?view=netframework-4.8).

**Comment by jridgewell** [comment]
Yah, the C# one was mentioned in https://github.com/jridgewell/proposal-array-select-reject/issues/1#issuecomment-545885335.

But Java? I'm not aware of a similarly named method. And I know nothing about LISP.

**Comment by motss** [comment]
I really like this idea. So I've added it to one of my packages [jsmodern](https://github.com/motss/jsmodern/blob/master/src/array/README.md) for TypeScript users (`deno` users should never miss this).

**Comment by jdalton** [comment]
Just popping in to register my dislike of an alias. I'm in favor of `reject` _(or `filterOut`, or whatever the final name is)_ though 👍

**Comment by jridgewell** [comment]
TC39 decided to reject (🥁) creating an alias, so we will not be getting a `select`. Closing this as resolved.

**Comment by shilangyu** [comment]
So this whole proposal can be closed then? Unless `reject` is still being considered?

**Comment by jridgewell** [comment]
No, TC39 is considering "making filtering easier", which means looking at the inverse function (`reject` or whatever we name it) and others like `partition`. The proposal reached Stage 1 with this as the direction.
